# Generated by Django 4.1.1 on 2022-09-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_blog_views_alter_blog_category'),
        ('authentication', '0003_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bookmarks',
            field=models.ManyToManyField(related_name='bookmarks', to='post.blog'),
        ),
    ]
