# Generated by Django 4.1.1 on 2022-09-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_blog_cover_image_blog_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=models.CharField(default='Summary was not provided :(', max_length=255),
        ),
    ]
