# Generated by Django 4.1.1 on 2022-09-17 08:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_blog_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Personal Blog'), (2, 'Business Blog'), (3, 'Technology Blog'), (4, 'Fashion Blog'), (5, 'Education Blog'), (6, 'Health and Fitness Blog'), (7, 'Food Blog'), (8, 'Sports Blog'), (9, 'Travel Blog'), (10, 'Lifestyle Blog'), (11, 'Photography Blog'), (12, 'Political Blog'), (13, 'Parenting Blog'), (14, 'Wedding Blog'), (15, 'Pet Blog'), (16, 'Home Décor Blog'), (17, 'DIY Blog'), (18, 'Marketing Blog'), (19, 'Entrepreneur Blog'), (20, 'Gaming Blog'), (21, 'Science Blog'), (22, 'Review Blog'), (23, 'Finance Blog'), (24, 'Music Blog'), (25, 'Movie Blog')], max_length=100),
        ),
    ]
