name: Docker CI

on:
  push:
    branches: ["main", "docker-ci"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create an empty .env file
        run: touch .env

      - name: Populate .env from secret
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build Docker Compose image
        run: docker-compose build

      - name: Start Docker Compose services
        run: docker-compose up -d

      - name: Run Pylint
        id: pylint
        run: |
          pylint_output=$(docker-compose exec --tty=false django-blog bash -c 'cd .. && pylint ignore=*/migrations/*.py blog/**/*.py')
          echo "$pylint_output"
          if [[ "$pylint_output" == *"10.00/10"* ]]; then
            echo "Pylint check passed"
          else
            echo "Pylint check failed"
            exit 1
          fi
        env:
          DOCKER_CLI_ACI: "1" # enables Application Container Image; it allows Docker to use the docker exec command

      - name: Stop Docker Compose services
        run: docker-compose down
