name: Docker CI

on:
  push:
    branches: ["main", "docker-ci"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create an empty .env file
        run: touch .env

      - name: Populate .env from secret
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build Docker Compose image
        run: docker-compose build

      - name: Start Docker Compose services
        run: docker-compose up -d

      - name: Install Requirements
        run: pip install -r test-requirements.txt

      - name: Run Pylint
        run: pylint blog/**/*.py

      - name: Stop Docker Compose services
        run: docker-compose down
