name: Docker CI

on:
  push:
    branches: ["main", "docker-ci"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create an empty .env file
        run: touch .env

      - name: Populate .env from secret
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build Docker Compose image
        run: docker-compose build

      - name: Start Docker Compose services
        run: docker-compose up -d

      - name: Run Pylint
        id: pylint
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of the current directory: $(ls)"
          docker-compose exec --tty=false django-blog bash -c 'cd .. && pylint blog/**/*.py'
        env:
          DOCKER_CLI_ACI: "1" # enables Application Container Image; it allows Docker to use the docker exec command

      - name: Stop Docker Compose services
        run: docker-compose down
