name: Docker CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create an empty .env file
        run: touch .env

      - name: Populate .env from secret
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build Docker image
        run: docker-compose build

      - name: Start Docker Compose services
        run: docker-compose up -d

      - name: Run Pylint
        id: pylint
        run: |
          pylint --output-format=text --ignore=*/migrations/*.py blog/**/*.py > pylint_report.txt
          pylint_exit_code=$?
          if [ $pylint_exit_code -eq 0 ]; then
            echo "Pylint passed with a perfect 10/10 score."
            echo "::set-output name=pylint_success::true"
          else
            echo "Pylint did not get a perfect score."
            echo "::set-output name=pylint_success::false"
          fi
        env:
          DOCKER_CLI_ACI: "1" # enables Application Container Image; it allows Docker to use the docker exec command

      - name: Stop Docker Compose services
        run: docker-compose down

      - name: Check Pylint result
        if: steps.pylint.outputs.pylint_success == 'true'
        run: echo "Pylint passed."
